import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import TopBar from '@/components/main/topBar';
import '../styles/globals.css';
import Script from 'next/script';
import { AuthProvider } from '@/components/AuthContext';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <AuthProvider>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          <Script src="//t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js" />
          <Script src="https://dapi.kakao.com/v2/maps/sdk.js?appkey=3ef1485c1295c74a6d065cdd5f6d61f3&libraries=services" />
          <div className="w-lvw h-lvh p-8 max-w-[1920px] mx-auto relative md:p-2">
            <TopBar />
            {children}
          </div>
        </body>
      </AuthProvider>
    </html>
  );
}
